backend:
  replicaCount: 1
  image:
    repository: zadcry/backend-app
    tag: "1.0.0"
  resources:
    requests:
      cpu: "50m" 
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
frontend:
  replicaCount: 1
  image:
    repository: zadcry/frontend-app
    tag: "1.1.1"

db:
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "1Gi"

    persistence:
      enabled: true
      storageClass: "do-block-storage"
      size: 1Gi

ingress:
  host: "dev.patrones.com"
