apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  # Construimos la URL de la DB usando el nombre del servicio del subchart de postgresql
  SPRING_DATASOURCE_URL: jdbc:postgresql://pedido-app-dev-db:5432/{{ .Values.db.auth.database }}