apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    # Anotación clave para reescribir/cortar las rutas
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.pathPrefix }}(/api/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-backend-service
            port:
              number: 80
      - path: {{ .Values.ingress.pathPrefix }}(/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-frontend-service
            port:
              number: 80