apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
data:
  # Helm base64-encodes these values automatically
  SPRING_DATASOURCE_USERNAME: {{ .Values.db.auth.username | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.db.auth.password | b64enc | quote }}